DECLARE
  lv_count number := 0;
BEGIN

  SELECT COUNT(*)
  INTO lv_count
  FROM DBA_USERS
  WHERE USERNAME = 'APEX_F1';

  IF lv_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER APEX_F1 CASCADE';
  END IF;

END;
/
-- USER SQL
CREATE USER "APEX_F1" IDENTIFIED BY "oracle"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

ALTER USER "APEX_F1" QUOTA UNLIMITED ON "USERS";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE TRIGGER TO "APEX_F1" ;
GRANT CREATE MATERIALIZED VIEW TO "APEX_F1" ;
GRANT CREATE VIEW TO "APEX_F1" ;
GRANT CREATE SESSION TO "APEX_F1" ;
GRANT CREATE TABLE TO "APEX_F1" ;
GRANT CREATE TYPE TO "APEX_F1" ;
GRANT CREATE SYNONYM TO "APEX_F1" ;
GRANT CREATE SEQUENCE TO "APEX_F1" ;
GRANT CREATE PROCEDURE TO "APEX_F1" ;
GRANT CREATE CLUSTER TO "APEX_F1" ;
GRANT CREATE DIMENSION TO "APEX_F1" ;
GRANT CREATE INDEXTYPE TO "APEX_F1" ;
GRANT CREATE JOB TO "APEX_F1" ;
GRANT CREATE OPERATOR TO "APEX_F1" ;
GRANT EXECUTE DYNAMIC MLE TO "APEX_F1" ;
